# Generated by Django 4.2.11 on 2026-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskdependency_id_alter_tasktag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='estimated_hours',
        ),
        migrations.AddField(
            model_name='subtask',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
