# Generated by Django 4.2.11 on 2026-02-03 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_taskdependency_id_alter_tasktag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text="e.g., 'priority_classifier'", max_length=100)),
                ('version', models.CharField(help_text="e.g., 'v1.2.0' or '2025-01-19'", max_length=50)),
                ('file_path', models.CharField(blank=True, help_text='Path to model weights (S3/local)', max_length=500, null=True)),
                ('config', models.JSONField(blank=True, help_text='Model hyperparameters', null=True)),
                ('metrics', models.JSONField(blank=True, help_text="e.g., {'accuracy': 0.95, 'f1_score': 0.93}", null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one active version per model_name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'indexes': [models.Index(fields=['model_name', 'is_active'], name='ai_modelver_model_n_8c5dfd_idx')],
                'unique_together': {('model_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(choices=[('breakdown_task', 'Breakdown Task'), ('suggest_priority', 'Suggest Priority')], max_length=100)),
                ('input_text', models.TextField()),
                ('output', models.JSONField(help_text='Model prediction payload')),
                ('latency_ms', models.IntegerField(help_text='Inference time in milliseconds')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score between 0.0 and 1.0', max_digits=3, null=True)),
                ('user_accepted', models.BooleanField(blank=True, help_text='Whether user accepted AI suggestion (for retraining)', null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_logs', to='ai.modelversion')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_logs', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inference Log',
                'verbose_name_plural': 'Inference Logs',
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_inferenc_user_id_d2251f_idx'), models.Index(fields=['endpoint'], name='ai_inferenc_endpoin_4d3a9a_idx'), models.Index(fields=['model_version'], name='ai_inferenc_model_v_a71e19_idx')],
            },
        ),
    ]
